[default]
SECRET_KEY="@jinja {{env.SECRET_KEY}}"
SQLALCHEMY_TRACK_MODIFICATIONS="@jinja {{env.SQLALCHEMY_TRACK_MODIFICATIONS}}"

MAIL_SENDER="@jinja {{env.MAIL_SENDER}}"
MAIL_SERVER="@jinja {{env.MAIL_SERVER}}"
MAIL_PORT="@jinja {{env.MAIL_PORT}}"
MAIL_USERNAME="@jinja {{env.MAIL_USERNAME}}"
MAIL_PASSWORD="@jinja {{env.MAIL_PASSWORD}}"
MAIL_USE_TLS="@jinja {{env.MAIL_USE_TLS}}"
MAIL_USE_SSL="@jinja {{env.MAIL_USE_SSL}}"

[development]
SQLALCHEMY_DATABASE_URI="@jinja {{env.SQLALCHEMY_DATABASE_URI_DEV}}"

[testing]
SQLALCHEMY_DATABASE_URI="@jinja {{env.SQLALCHEMY_DATABASE_URI_TESTING}}"