"""empty message

Revision ID: 9b18d73fe238
Revises: be69e9837dad
Create Date: 2023-04-18 19:23:08.462510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b18d73fe238'
down_revision = 'be69e9837dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=84), nullable=False))
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
